Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  config.vm.define "server" do |server|
    
    # static private IP
    server.vm.network "private_network", ip: "192.168.56.10"

    # machine name
    server.vm.hostname = "server"

    # VM resources
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "3048"
      vb.cpus = 2
    end

  end

end
