Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  config.vm.define "server" do |server|

    # sync current folder -> VM
    config.vm.synced_folder "../ansible", "/home/vagrant/project/ansible"
    config.vm.synced_folder "../docker", "/home/vagrant/project/docker"
    
    # static private IP
    server.vm.network "private_network", ip: "192.168.56.10"

    # machine name
    server.vm.hostname = "server"

    # VM resources
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "3048"
      vb.cpus = 2
    end
    server.vm.provision "shell", path: "./scripts/setup.sh"

  end

end
