services:
  wordpress:
    image: wordpress:6.4-php8.2
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - /opt/data/wordpress:/var/www/html

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - wordpress
    volumes:
      - ./nginx/aws-wordpress.conf:/etc/nginx/conf.d/default.conf:ro