- name: Copy docker-compose file
  copy:
    src: "{{ playbook_dir }}/../docker/docker-compose.yml"
    dest: "/home/{{ ansible_user }}/docker-compose.yml"

- name: Start containers
  command: docker-compose up -d
  args:
    chdir: "/home/{{ ansible_user }}"