- name: Install OpenSSL
  apt:
    name: openssl
    state: present

- name: Create directory for SSL certificates
  file:
    path: /etc/nginx/ssl
    state: directory

- name: Generate self-signed SSL certificate
  command: >
    openssl req -x509 -nodes -days 365 -newkey rsa:2048
    -keyout /etc/nginx/ssl/nginx.key
    -out /etc/nginx/ssl/nginx.crt
    -subj "/C=FR/ST=IDF/L=Paris/O=42/OU=Cloud-1/CN=localhost"
  args:
    creates: /etc/nginx/ssl/nginx.crt

